config/routes.rb
Rails.application.routes.draw do

  root 'github_fetchers#index'

  get '/auth/:provider/callback', to: 'tweets#index'

  resources :github_fetchers
  resources :tweets

end

app/models/github_fetcher.rb
class GithubFetcher
  attr_reader :client

  def initialize
    @client = Octokit::Client.new(:access_token => Rails.application.secrets.access_token)
    @client.user.login
  end

end

app/models/tweet.rb
class Tweet

  def initialize
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['consumer_key']
      config.consumer_secret = ENV['consumer_secret']
      config.access_token =ENV['access_token_twitter']
      config.access_token_secret =ENV['access_token_secret']
    end
  end

  def user_tweets(user_id)
    @client.user_timeline(user_id)
  end

  def make_tweet(the_tweet)
    @client.update(the_tweet)
  end

  def home_time
    @client.home_timeline
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_fetchers_controller.rb
class GithubFetchersController < ApplicationController

  def index
    @fetcher = GithubFetcher.new
    # binding.pry
    if params[:user_name]
      @entered = @fetcher.client.user(params[:user_name])
    end
    if params[:user_name_for_repos]
      @repos = @fetcher.client.repositories(params[:user_name_for_repos])
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweet = Tweet.new
    @messages = []
    unless params[:entered].blank?
      @tweets = @tweet.user_tweets(params[:entered][:u_n])
    end
    if params[:message]
      @tweet.make_tweet(params[:message])
      @messages << "Tweeted"
    end

    @home_feed =@tweet.home_time
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github_fetchers/index.html.erb
<h1 class= "page-header header">GitHub Dashboard</h1>
<%= link_to "The Twittle", tweets_path %>
<br>
<%= "<strong>Your Location: </strong>".html_safe + @fetcher.client.user.location%>
<br>
<br>

<%= form_tag github_fetchers_path, method: :get do %>
<strong>Enter Git Hub User Name</strong>
<%= text_field_tag :user_name %>
<%= submit_tag "Get Info" %>
<% end %>





<% if @entered %>

<%= image_tag @entered.avatar_url %>

<table>
<tr>
  <td>
    <strong>Username:</strong>
  </td>
  <td>
    <%=@entered.login %>
  </td>
</tr>
<tr>
  <td>
    <strong>User ID:</strong>
  </td>
  <td>
    <%=@entered.id %>
  </td>
</tr>
<tr>
  <td>
    <strong>Name:</strong>
  </td>
  <td>
    <%=@entered.name %>
  </td>
</tr>


</table>
<% end %>

<br>

<%= form_tag github_fetchers_path, method: :get do %>
<strong>Enter Git Hub User Name</strong>
<%= text_field_tag :user_name_for_repos %>
<%= submit_tag "Get Repository Names" %>
<% end %>
<br>

<% if @repos %>
<h2>Repositories</h2>
<% @repos.each do |field| %>
<%= field.name  %><br>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitHubLecture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1 class= "header page-header"> The Twittle</h1>
<%= link_to "Github Dashboard", github_fetchers_path %>
<br>
<br>
<% if @messages %>
<% @messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<%= form_for :entered, {url: tweets_path, method: :get} do |f| %>
<%= f.label "Enter Somones Twitter Handle" %>
<%= f.text_field :u_n %>
<%= f.submit "Get Tweets" %>
<% end %>
<br>
<br>

<%= form_tag '/', method: :get do %>
<%= text_field_tag :message %>
<%= submit_tag "Tweet" %>
<% end %>
<br>

<% unless params[:entered].blank? %>
<strong> <%= "These are the last 20 tweets from #{params[:u_n]}" %></strong>

<table class= "table">
  <% @tweets.each do |tweet| %>
  <tr>
    <td>
      <%= tweet.text %>
    </td>
  </tr>
  <% end %>
</table>
<% end %>

<strong>  <%= "This is my home feed" %></strong>
<table class= "table">
  <% @home_feed.each do |tweet| %>
  <tr>
    <td>
      <%= tweet.text %>
    </td>
  </tr>
  <% end %>
</table>